image: docker:20.10.7

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

build:
  stage: build
  before_script:
    - apk add --no-cache maven  # Install Maven
  script:
    - chmod +x ./automate_backend_build.sh
    - ./automate_backend_build.sh
