# -*- mode: ruby -*-
#
# vi: set ft=ruby :
# vim: ts=2

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "stage-vm"
  config.vm.box_download_insecure = false 
  
  ENV['LC_ALL']="en_US.UTF-8"
  

  config.vm.network :private_network, ip: "192.168.56.7"

  config.vm.synced_folder "../../data", "/vagrant_data"
  config.vm.synced_folder "./stage-scripts", "/home/vagrant/scripts"

  config.vm.provider :virtualbox do |vb|
   
    vb.customize [
      'modifyvm', :id,
      '--natdnshostresolver1', 'on',
      '--memory', '4096',
      '--cpus', '1'
    ]
    
  end
  config.vm.boot_timeout = 300  # 5 minutes
  config.vm.graceful_halt_timeout = 60
  
  config.vm.provision "shell", inline: <<-SHELL
     	sudo apt-get update
     	sudo apt-get install --yes python
   	SHELL

  # Create directories and set permissions
  config.vm.provision "shell", inline: <<-SHELL
    cp -r /vagrant_data/stage-frontend /home/vagrant/
    # Copy the stage-backend directory from /vagrant_data to /home/vagrant
    cp -r /vagrant_data/stage-backend /home/vagrant/
    chmod 777 /home/vagrant/stage-frontend
    chmod 777 /home/vagrant/stage-backend
  SHELL
  
  config.vm.provision "shell", inline: <<-SHELL
      chmod +x /home/vagrant/scripts/setup-gitlab-runner-stage-vm.sh
      /home/vagrant/scripts/setup-gitlab-runner-stage-vm.sh
   SHELL
  
  
   
  
end
