before_script:
  - export CURRENT_DATETIME=`date +"%Y%m%d-%H%M%S"`

stages:
  - build
  - deploy


services:
  - name: docker:dind

build:
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: node:15
  stage: build
  tags: [e4l-frontend]
  script: npm install && npm run build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - e4l.frontend.docker/web/dist
  artifacts:
    paths:
      - e4l.frontend.docker/web/dist
    expire_in: 1 week


deploy:
  stage: deploy
  tags:
    - stage-vm-frontend-shell
  image: ubuntu:latest  # Use an image with ssh/scp installed
  script:
    - apt-get update && apt-get install -y openssh-client  # Install SSH client for scp
    - mkdir -p /home/vagrant/artefact-repository  # Local directory to hold the artifacts temporarily
    - cp e4l.frontend.docker/web/dist/* /home/vagrant/artefact-repository  # Copy artifacts locally
    # Use scp to transfer the artifacts to the remote VM
    - scp -o StrictHostKeyChecking=no -r /home/vagrant/artefact-repository/* vagrant@192.168.56.7:/desired/remote/path
  dependencies:
    - build  # Ensures artifacts from the build stage are available
