before_script:
  - export CURRENT_DATETIME=`date +"%Y%m%d-%H%M%S"`

stages:
  - build


services:
  - name: docker:dind

build:
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: node:15
  stage: build
  tags: [e4l-frontend]
  script: npm install && npm run build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - e4l.frontend.docker/web/dist
  artifacts:
    paths:
      - e4l.frontend.docker/web/dist
    expire_in: 1 week


